CREATE TABLE "public"."Account" (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    balance INTEGER NOT NULL,
    velocity INTEGER NOT NULL,
    is_member BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    is_bank BOOLEAN NOT NULL DEFAULT FALSE,
    pending_approval BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "public"."Transaction" (
    id SERIAL PRIMARY KEY NOT NULL,
    amount INTEGER NOT NULL,
    message VARCHAR NOT NULL,
    sender INTEGER NOT NULL,
    recipient INTEGER NOT NULL,
    is_taxable BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY ("sender") REFERENCES "public"."Account"(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY ("recipient") REFERENCES "public"."Account"(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE "ListingType" AS ENUM ('offer', 'request');
CREATE TYPE "ListingStatus" AS ENUM ('active', 'complete', 'delisted');

CREATE TABLE "public"."Listing" (
    id SERIAL PRIMARY KEY NOT NULL,
    author INTEGER NOT NULL,
    type "ListingType" NOT NULL,
    message VARCHAR NOT NULL,
    reward INTEGER NOT NULL,
    contact VARCHAR,
    status "ListingStatus" NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("author") REFERENCES "public"."Account"(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);